# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# Setup
title:               Asymptotically Trivial
tagline:             'A personal blog on statistics, maths, and coding.'
description:         ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Chao Guo
  url:               
  email:             

# Custom vars
version:             1.0.0
